Rock-n-Block/less-nft

src/pages/Home/HotAuction/components/PaymentComponent/index.tsx
src/styles/blocks/slick.scss

slider image max-height

---

src/components/Chart/index.tsx

fixed priceHistory price

---

src/components/Header/MobileMenu/index.tsx
src/containers/Footer/index.tsx

UI8 => Lessnft

---

src/components/TabLookingComponent/styles.module.scss

fixed tabs color in profile

---

src/components/Checkout/index.tsx
src/components/PlaceBid/index.tsx
src/pages/Home/HotAuction/components/PaymentComponent/index.tsx
src/store/Modals.ts
src/typings/index.ts

fixed 1155 purchase, place a bid

fixed 1155 purchase, place a bid

---

src/pages/CollectionPage/CollectionMainInfo/CollectionMainInfo.module.scss
src/pages/CollectionPage/CollectionMainInfo/index.tsx
src/pages/CollectionPage/index.tsx
src/services/api/store.ts

added change collection banner

added change collection banner

---

src/pages/CollectionPage/CollectionMainInfo/CollectionMainInfo.module.scss

added gap in collection main info banner button

added gap in collection main info banner button

---

src/components/GiantArtCard/styles.module.scss
src/pages/CollectionPage/CollectionMainInfo/CollectionMainInfo.module.scss
src/pages/CollectionPage/CollectionMainInfo/index.tsx

banner edit button text, giantCard fixes

banner edit button text, giantCard fixes

---

src/pages/Nft/index.tsx
src/pages/Profile/UserMainInfo/UserMainInfo.module.scss
src/pages/Profile/UserMainInfo/index.tsx

fixed text in edit buttons on User profile, added noItems in related artworks

fixed text in edit buttons on User profile

---

src/pages/Profile/UserMainInfo/index.tsx

changed unfollow button

---

src/components/Header/Search/components/SearchTag/index.tsx
src/components/Header/Search/index.tsx
src/components/Transfer/index.tsx
src/services/walletConnect/index.tsx

removed history.push after connect, search placeholder, price in search

removed history.push after connect, search placeholder, price in search

---

src/config/index.ts

exchange ethereum

---

src/containers/Footer/index.tsx
src/containers/Footer/styles.module.scss
src/pages/Home/CreateAndSellNft/index.tsx
src/services/walletConnect/index.tsx

fixed footer, redirect, start selling now

fixed footer, redirect, start selling now

---

src/components/LiveAuction/index.tsx

fixed live auction noItems

---

src/components/Checkout/index.tsx
src/forms/Create/component/index.tsx

fixed choose seller price, digital key placeholder

fixed choose seller price, digital key placeholder

---

src/hooks/useTabs.ts
src/pages/Discover/index.tsx

fixed search by text

---

src/components/RangePicker/index.tsx
src/containers/AdvancedFilter/index.tsx
src/hooks/useFilters.ts

fixed input in rangepicker

---

src/components/ActivityItem/ActivityItem.module.scss
src/components/Header/styles.module.scss
src/config/index.ts
src/containers/Footer/styles.module.scss
src/pages/Activity/Activity.module.scss
src/pages/Home/CreateAndSellNft/styles.module.scss

activity image
home ourArtworks text center

mobile bugfixes

---

src/components/Control/Control.module.scss
src/components/Header/HeaderLinks/index.tsx
src/forms/Create/component/CreateCollectibleDetails.module.scss
src/forms/CreateCollection/component/CreateCollection.module.scss
src/forms/Profile/component/ProfileEdit.module.scss
src/hooks/useTabs.ts
src/pages/Discover/styles.module.scss

user tabs
create collection Upload button

mobile fixes 3

---

src/forms/Create/component/CreateCollectibleDetails.module.scss

fixed add delete properties

---

src/containers/AdvancedFilter/index.tsx
src/hooks/useFilters.ts
src/pages/Discover/index.tsx

textSearch filter

---

src/components/Header/Search/index.tsx

fixed searchItem selling

---

src/pages/Home/HotAuction/components/PaymentComponent/index.tsx

added logs

---

src/components/ChangePrice/index.tsx
src/components/Header/User/index.tsx

my collctibles in User popover, change price button color

my collctibles in User popover, change price button color

---

src/hooks/useFetchTags.ts

fixed tags

---

src/components/Button/styles.module.scss
src/components/Header/User/index.tsx
src/components/LiveAuction/LiveAuction.module.scss
src/components/Select/styles.module.scss
src/forms/Create/component/index.tsx
src/pages/Home/BrowseByCategory/styles.module.scss
src/pages/Home/ResourceForGettingStarted/styles.module.scss
src/pages/Home/Trending/TitleDropdown/index.tsx
src/pages/Home/Trending/index.tsx
src/pages/Profile/Tabs/Collections/index.tsx
src/pages/Profile/index.tsx

trending all nfts
margins on main page
fix properties clear after changing standart

bugfixes main page, create token

---

src/components/Details/index.tsx
src/components/TextInput/index.tsx
src/styles/common.scss

fixed details delete

---

src/components/DiscoverFilters/components/CollectionsFilter/index.tsx

trying to fix build

---

src/hooks/useFetchTopCollections.ts

fixed useFetchTopCollections

---

src/pages/Discover/index.tsx

text results discover bold

---

src/pages/Discover/index.tsx
src/pages/Discover/styles.module.scss

hide live auction in discover

---

src/appConstants/routes.ts
src/components/PutSale/index.tsx
src/pages/Home/TopCollections/index.tsx
src/pages/TopNfts/index.tsx
src/services/api/store.ts

fixed topnfts Link to collection and period after redirect

fixed topnfts Link to collection and period after redirect

---

src/pages/Home/HotAuction/components/AuthorComponent/index.tsx

hide default collection on token page

hide default collection on token page

---

src/components/PutSale/index.tsx
src/pages/Home/HotAuction/components/PaymentComponent/index.tsx
src/pages/Home/HotAuction/components/PaymentComponent/styles.module.scss
src/services/api/rates.ts

time format, multi currnecies

---

src/components/Checkout/index.tsx
src/components/ChooseWallet/index.tsx
src/config/index.ts
src/hooks/useGetUserAccessForNft.ts

fixes 1155 reject buy, hide timed auc

fixes 1155 reject buy, hide timed  auc

---

src/hooks/useGetUserAccessForNft.ts
src/pages/Home/Trending/index.tsx
src/pages/Home/Trending/styles.module.scss

tranding margin fix, try to fix timed buttons

tranding margin fix, try to fix timed buttons

---

src/forms/Create/component/index.tsx

time auc only for single

---

src/hooks/useGetUserAccessForNft.ts

timed auc put/place bid fixes

---

src/hooks/useFetchNft.ts
src/services/api/store.ts

fixed reload profile, has_bids

fixed reload profile, has_bids

---

src/hooks/useFetchNft.ts

fixed debounced to 1 min

---

src/pages/Home/Trending/index.tsx
src/pages/Home/Trending/styles.module.scss

fix trending a few items

---

src/components/GiantArtCard/styles.module.scss
src/pages/Home/HotAuction/components/PaymentComponent/index.tsx
src/pages/Home/HotAuction/components/PaymentComponent/styles.module.scss

timed auc paymentComponent

---

src/components/GiantArtCard/styles.module.scss
src/pages/Home/HotAuction/components/PaymentComponent/styles.module.scss
src/pages/Home/HotAuction/components/ViewsAndControlsComponent/styles.module.scss

buttons on payment component

---

src/components/GiantArtCard/index.tsx

fix isWrongChain

---

src/pages/Home/HotAuction/components/PaymentComponent/index.tsx

timed auc timer

---

src/components/ArtCard/styles.module.scss
src/components/Select/index.tsx
src/components/Select/styles.module.scss
src/components/TextInput/index.tsx
src/containers/Footer/components/FooterEmail/index.tsx
src/containers/Footer/styles.module.scss

footer fixes: fonts, email. Select menu overflow-y

footer fixes: fonts, email. Select menu overflow-y

---

src/components/ArtCard/index.tsx
src/pages/Discover/components/Labels/index.tsx
src/pages/Home/Trending/index.tsx

hide clear all button

---

src/containers/Footer/components/FooterEmail/index.tsx

clear email field after saving

clear email field after saving

---

src/components/Button/index.tsx
src/components/Chart/Chart.module.scss
src/forms/Create/component/index.tsx
src/hooks/useFetchNft.ts

refresh tokens on profile page, buttons blue color

refresh tokens on profile page, buttons blue color

---

src/components/DiscoverFilters/components/GroupWrapper/index.tsx
src/components/GiantArtCard/styles.module.scss
src/components/Header/styles.module.scss
src/components/Typography/styles.module.scss
src/pages/Home/Banner/styles.module.scss
src/pages/Home/HotAuction/components/PaymentComponent/styles.module.scss
src/pages/Home/HotAuction/components/ViewsAndControlsComponent/styles.module.scss

added style for payment component, fonts changing

added style for payment component, fonts changing

---

src/components/RemoveSale/index.tsx
src/core/axios.ts
src/hooks/useFetchNft.ts
src/pages/Home/HotAuction/components/ViewsAndControlsComponent/index.tsx
src/services/api/store.ts
src/store/Modals.ts

fixed currency removeFromSale, useFetchNft

fixed currency removeFromSale, useFetchNft

---

src/components/RemoveSale/index.tsx
src/pages/Home/HotAuction/components/ViewsAndControlsComponent/index.tsx
src/services/api/store.ts
src/store/Modals.ts

fixed removeFromSale

---

src/components/PutSale/index.tsx

hide trx on auc putSale

---

src/containers/Popover/PopoverBody/styles.module.scss

fix wallet modal

---

src/components/Swap/index.tsx
src/pages/Profile/Tabs/TabHeader/TabHeader.module.scss

mobile fizes Swap max amount

---

src/components/PutSale/index.tsx
src/pages/CollectionPage/index.tsx
src/pages/Discover/index.tsx

putOnSale fixes

---

src/components/Header/Search/components/SearchTag/index.tsx
src/components/Header/Search/index.tsx

fix search

---

src/pages/Profile/Tabs/TabHeader/TabHeader.module.scss

more gap for tab_header

---

src/components/LiveAuction/index.tsx

live auction today h3 -> h2

---

src/pages/TopNfts/index.tsx
src/pages/TopNfts/styles.module.scss

top nfts fixes

---

src/pages/TopNfts/styles.module.scss

top nfts body open to top
